artifact_config:
  artifacts_dir: artifacts

data_ingestion_config:
  dataset_download_url:  arashnic/book-recommendation-dataset
  dataset_dir: dataset
  ingested_dir: ingested_data
  raw_data_dir: raw_data

data_validation_config:
  clean_data_dir: clean_data
  serialized_object_dir: serialized_objects
  books_file: Books.csv
  ratings_file: Ratings.csv


data_transformation_config:
  transformed_data_dir: transformed_data 

model_training_config:
  trained_model_dir: trained_model
  model_file: model.pkl

recommendation_config:
  book_name_serialized_file: book_names.pkl
  book_pivot_serialized_file: book_pivot.pkl
  final_rating_serialized_file: final_rating.pkl
  trained_model_path: trained_model
  trained_model_name: model.pkl
  num_recommendations: 6